name: Run with Gradle

on:
  workflow_dispatch:

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
            distribution: "zulu"
            java-version: 11


      - name: Install Google Chrome # Using shell script to install Google Chrome
        run: |
          chmod +x ./scripts/InstallChrome.sh
           ./scripts/InstallChrome.sh
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # give permission to Gradle to run the

      - name: Build with Gradle
        run: gradle clean test -Pserver=local
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        name: Upload Report Artifacts
        with:
          name: allure-report
          path: /${{ github.workspace }}/build/allure-results/

  upload_allure_report:
    if: always()
    needs: build
    name: Upload Allure Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        name: Download uploaded artifacts
        with:
          name: allure-report
          path: /${{ github.workspace }}/build/allure-results/